spring:
   application:
      name: property-chatbot-backend

   quartz:
      job-store-type: memory


   ai:
     openai:
        api-key: ${OPENAI_API_KEY}

   datasource:
      url: jdbc:postgresql://localhost:5432/property_chatbot
      username: postgres
      password: postgres


   jpa:
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

server:
   port: 8085





app:
   jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
   jwt-expiration-milliseconds: 604800000

logging:
   level:
      com.milton.propertychatbotbackend: DEBUG
      org.springframework.security: DEBUG





